name: CI
on: [push]
env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.84.1
jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust ${{ env.RUST_VERSION }}
        run: rustup toolchain install ${{ env.RUST_VERSION }} --component clippy --component rustfmt && rustup default ${{ env.RUST_VERSION }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all
      - name: Run tests
        run: cargo test --all
      - name: Run clippy
        run: cargo clippy --all -- -D warnings
      - name: Run fmt
        run: cargo fmt --all -- --check
